name: CI

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Compile
      run: mvn clean test-compile -B

    - name: Test
      run: mvn verify -B -Dmaven.test.skip=true

    - name: Build docker image
      run: docker build -f Dockerfile -t pizzaria-api:latest .

    - name: Remove deploy
      continue-on-error: true
      run: docker stack rm pizzaria-api
      
    - name: Deploy Docker Swarm
      run: docker stack deploy --compose-file docker-service-pizzaria.yml pizzaria-api
    
